// <auto-generated />
using DAL_net.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL_net.Persistence.Migrations
{
    [DbContext(typeof(GeologyDbContext))]
    [Migration("20260504184500_InitialGeologySchema")]
    partial class InitialGeologySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralCharacteristicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cleavage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cleavage");

                    b.Property<string>("Color")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("color");

                    b.Property<string>("Fracture")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fracture");

                    b.Property<decimal?>("HardnessMohs")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("hardness_mohs");

                    b.Property<string>("Luster")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("luster");

                    b.Property<bool>("Magnetism")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("magnetism");

                    b.Property<int>("MineralId")
                        .HasColumnType("integer")
                        .HasColumnName("mineral_id");

                    b.Property<string>("Morphology")
                        .HasColumnType("text")
                        .HasColumnName("morphology");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Paragenesis")
                        .HasColumnType("text")
                        .HasColumnName("paragenesis");

                    b.Property<string>("SpecialProperties")
                        .HasColumnType("text")
                        .HasColumnName("special_properties");

                    b.Property<decimal?>("SpecificGravity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("specific_gravity");

                    b.Property<string>("Streak")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("streak");

                    b.Property<string>("Tenacity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenacity");

                    b.Property<string>("Transparency")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("transparency");

                    b.HasKey("Id");

                    b.HasIndex("MineralId")
                        .IsUnique()
                        .HasDatabaseName("idx_mineral_char_mineral");

                    b.ToTable("mineral_characteristics", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Analogy")
                        .HasColumnType("text")
                        .HasColumnName("analogy");

                    b.Property<string>("ChemicalNote")
                        .HasColumnType("text")
                        .HasColumnName("chemical_note");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("mineral_classes", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChemicalFormula")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chemical_formula");

                    b.Property<string>("CommonUse")
                        .HasColumnType("text")
                        .HasColumnName("common_use");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MineralClassId")
                        .HasColumnType("integer")
                        .HasColumnName("mineral_class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SilicateStructureId")
                        .HasColumnType("integer")
                        .HasColumnName("silicate_structure_id");

                    b.HasKey("Id");

                    b.HasIndex("MineralClassId")
                        .HasDatabaseName("idx_minerals_class");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SilicateStructureId")
                        .HasDatabaseName("idx_minerals_silicate");

                    b.ToTable("minerals", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NotableNote")
                        .HasColumnType("text")
                        .HasColumnName("notable_note");

                    b.Property<int>("SubtypeId")
                        .HasColumnType("integer")
                        .HasColumnName("subtype_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SubtypeId")
                        .HasDatabaseName("idx_rocks_subtype");

                    b.ToTable("rocks", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockMineralCompositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abundance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("abundance");

                    b.Property<int>("MineralId")
                        .HasColumnType("integer")
                        .HasColumnName("mineral_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RockId")
                        .HasColumnType("integer")
                        .HasColumnName("rock_id");

                    b.HasKey("Id");

                    b.HasIndex("MineralId")
                        .HasDatabaseName("idx_rmc_mineral");

                    b.HasIndex("RockId")
                        .HasDatabaseName("idx_rmc_rock");

                    b.HasIndex("RockId", "MineralId")
                        .IsUnique();

                    b.ToTable("rock_mineral_composition", null, t =>
                        {
                            t.HasCheckConstraint("CK_rock_mineral_composition_abundance", "abundance IN ('major', 'minor', 'trace')");
                        });
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockSubtypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FormationNote")
                        .HasColumnType("text")
                        .HasColumnName("formation_note");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RockTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("rock_type_id");

                    b.HasKey("Id");

                    b.HasIndex("RockTypeId")
                        .HasDatabaseName("idx_rock_subtypes_type");

                    b.HasIndex("RockTypeId", "Name")
                        .IsUnique();

                    b.ToTable("rock_subtypes", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OriginNote")
                        .HasColumnType("text")
                        .HasColumnName("origin_note");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("rock_types", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.SilicateStructureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Analogy")
                        .HasColumnType("text")
                        .HasColumnName("analogy");

                    b.Property<string>("IupacName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("iupac_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("StructureDesc")
                        .HasColumnType("text")
                        .HasColumnName("structure_desc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("silicate_structures", (string)null);
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralCharacteristicEntity", b =>
                {
                    b.HasOne("DAL_net.Persistence.Entities.MineralEntity", "Mineral")
                        .WithOne("Characteristic")
                        .HasForeignKey("DAL_net.Persistence.Entities.MineralCharacteristicEntity", "MineralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mineral");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralEntity", b =>
                {
                    b.HasOne("DAL_net.Persistence.Entities.MineralClassEntity", "MineralClass")
                        .WithMany("Minerals")
                        .HasForeignKey("MineralClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL_net.Persistence.Entities.SilicateStructureEntity", "SilicateStructure")
                        .WithMany("Minerals")
                        .HasForeignKey("SilicateStructureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MineralClass");

                    b.Navigation("SilicateStructure");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockEntity", b =>
                {
                    b.HasOne("DAL_net.Persistence.Entities.RockSubtypeEntity", "Subtype")
                        .WithMany("Rocks")
                        .HasForeignKey("SubtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtype");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockMineralCompositionEntity", b =>
                {
                    b.HasOne("DAL_net.Persistence.Entities.MineralEntity", "Mineral")
                        .WithMany("RockCompositions")
                        .HasForeignKey("MineralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL_net.Persistence.Entities.RockEntity", "Rock")
                        .WithMany("MineralCompositions")
                        .HasForeignKey("RockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mineral");

                    b.Navigation("Rock");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockSubtypeEntity", b =>
                {
                    b.HasOne("DAL_net.Persistence.Entities.RockTypeEntity", "RockType")
                        .WithMany("Subtypes")
                        .HasForeignKey("RockTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RockType");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralClassEntity", b =>
                {
                    b.Navigation("Minerals");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.MineralEntity", b =>
                {
                    b.Navigation("Characteristic");

                    b.Navigation("RockCompositions");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockEntity", b =>
                {
                    b.Navigation("MineralCompositions");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockSubtypeEntity", b =>
                {
                    b.Navigation("Rocks");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.RockTypeEntity", b =>
                {
                    b.Navigation("Subtypes");
                });

            modelBuilder.Entity("DAL_net.Persistence.Entities.SilicateStructureEntity", b =>
                {
                    b.Navigation("Minerals");
                });
#pragma warning restore 612, 618
        }
    }
}
